### ISSUE TITLE
Override Admin Login Page

### ISSUE THREAD

**Issue by payton** [payton/django-siwe-auth#16] opened 2022-05-24 03:09 UTC
Currently, the Django admin login page defaults to password authentication. This is no longer plausible for key-pair authentication.

Issue identified in https://github.com/payton/django-siwe-auth/issues/15

**Comment by pconerly** [comment] 2022-06-01 08:41
This is also a duplicate of https://github.com/payton/django-siwe-auth/issues/7

But the link is valuable https://docs.djangoproject.com/en/dev/ref/contrib/admin/#root-and-login-templates

**Closed** 2022-08-14 12:20 UTC
Labels: bug
